M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 23 21:23:26 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-23T21:23:26-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.9Y-4.2
X6.0Y-4.4
X6.4Y-4.2
X6.4Y-4.4
T2
X6.1Y-4.0
X6.3Y-4.0
T0
M30
